export const ERROR_CODES = {
    // authentication and user errors
    INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
    INVALID_EMAIL: "INVALID_EMAIL",
    INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
    INVALID_USERNAME: "INVALID_USERNAME",
    EMAIL_EXISTS: "EMAIL_EXISTS",
    FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
    EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
    INVALID_EMAIL_AUTHENTICATION_METHOD: "INVALID_EMAIL_AUTHENTICATION_METHOD",
    INVALID_GOOGLE_AUTHENTICATION_METHOD: "INVALID_GOOGLE_AUTHENTICATION_METHOD",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    INVALID_AUTHORIZATION_TOKEN: "INVALID_AUTHORIZATION_TOKEN",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    PROFILE_UPDATE_FAILURE: "PROFILE_UPDATE_FAILURE",

    // asset-related errors
    INVALID_SEARCH_QUERY: "INVALID_SEARCH_QUERY",
    FETCH_OPERATION_FALIURE: "FETCH_OPERATION_FALIURE",
    INVALID_ASSET_SYMBOL: "INVALID_ASSET_SYMBOL",
    INVALID_CHART_DATA_RANGE: "INVALID_CHART_DATA_RANGE",
    INVALID_ASSET_UNITS: "INVALID_ASSET_UNITS",
    PORTFOLIO_OPERATION_FAILURE: "PORTFOLIO_OPERATION_FAILURE",
    ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
    INVALID_PORTFOLIO_QUERY: "INVALID_PORTFOLIO_QUERY",
    WATCHLIST_OPERATION_FAILURE: "WATCHLIST_OPERATION_FAILURE",

    // alert-related errors
    INVALID_ALERT_CONDITION: "INVALID_ALERT_CONDITION",
    INVALID_ALERT_TARGET_PRICE: "INVALID_ALERT_TARGET_PRICE",
    INVALID_ALERT_TITLE: "INVALID_ALERT_TITLE",
    INVALID_ALERT_MESSAGE: "INVALID_ALERT_MESSAGE",
    ALERT_OPERATION_FAILURE: "ALERT_OPERATION_FAILURE",
    INVALID_ALERT_ID: "INVALID_ALERT_ID",
    ALERT_NOT_FOUND: "ALERT_NOT_FOUND",

    // frontend crash error
    FRONTEND_ERROR: "FRONTEND_ERROR"
}